### ISSUE TITLE
LG K10 doesn't read the barcodes with the library

### ISSUE THREAD

**Issue by rodrigoramosDC** [trevorwang/flutter-zxing#1]
When I try read barcodes with LG K10 the Example Restarts. 

It is possible to verify?

My logcat:
2019-02-11 16:28:23.072 13146-13146/tv.---.localhost E/onDestroy(): stopHandler Ended
2019-02-11 16:28:23.100 13146-13146/tv.---.localhost E/WindowManager: android.view.WindowLeaked: Activity mingsin.fzxing.CaptureActivity has leaked window DecorView@10fb9d1[Position the bar code within this box] that was originally added here
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:431)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:331)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
        at android.app.Dialog.show(Dialog.java:337)
        at mingsin.fzxing.CaptureActivity.showDialogForRestart(CaptureActivity.kt:229)
        at mingsin.fzxing.CaptureActivity.access$showDialogForRestart(CaptureActivity.kt:25)
        at mingsin.fzxing.CaptureActivity$startHandler$1.run(CaptureActivity.kt:198)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6312)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
2019-02-11 16:28:23.528 13146-13146/tv.---.localhost W/IInputConnectionWrapper: reportFullscreenMode on inexistent InputConnection
2019-02-11 16:28:25.521 13146-13146/tv.----.localhost D/FlutterNativeView: FlutterView.send called on a detached view, channel=lyokone/locationstream
2019-02-11 16:28:28.042 13146-13157/tv.---.localhost I/MediaPlayer-JNI: release
2019-02-11 16:28:45.612 13146-13146/tv.---.localhost D/FlutterNativeView: FlutterView.send called on a detached view, channel=lyokone/locationstream

**Comment by rodrigoramosDC** [comment]
2019-02-11 16:03:52.046 1126-1582/? E/sensors_hal_nusensors: handleToDriver handle(0)
2019-02-11 16:03:52.046 1126-1582/? E/sensors_hal_nusensors: go to batchsensor(0)
2019-02-11 16:03:52.059 554-4269/? E/Drv/IMem: Drv/IMem[vendor/mediatek/proprietary/hardware/mtkcam/legacy/platform/mt6755/core/drv/imem/imem_drv.cpp, init, line0198] ERROR: open dbg file fail(/sdcard/ispdbg/imemleakDBG.txt,,,2) (init){#198:vendor/mediatek/proprietary/hardware/mtkcam/legacy/platform/mt6755/core/drv/imem/imem_drv.cpp}
2019-02-11 16:03:52.210 1764-1832/? E/PerfService::ph_mtk: ph_apply_hint::hint=27132904, lge_id=1000, en=68 is not supported
2019-02-11 16:03:52.227 554-4269/? E/BWC: MTK_IOC_MMDVFS_CMD failed.:Bad address
2019-02-11 16:03:52.228 554-4269/? E/BWC: MTK_IOC_MMDVFS_CMD failed.:Bad address
2019-02-11 16:03:52.241 1126-17690/? E/sensors_hal_nusensors: handleToDriver handle(0)

**Comment by trevorwang** [comment]
@rodrigoramosDC Can you provide some sample code?

Or you add some code to CaptureActivity?
```
at mingsin.fzxing.CaptureActivity.showDialogForRestart(CaptureActivity.kt:229)
at mingsin.fzxing.CaptureActivity.access$showDialogForRestart(CaptureActivity.kt:25)
at mingsin.fzxing.CaptureActivity$startHandler$1.run(CaptureActivity.kt:198)
```

**Comment by rodrigoramosDC** [comment]
Man, when I use the sample code (example-app) in LG K10 (My Boss Phone) the
app restarts and doesn't read the barcode. But the code works in Motorola
and Samsung and emulators like Pixel, Nexus and others...

If you want, I could write a contract in UpWork.com to solve this problem.
What do you think?

Tks man.

**Comment by rodrigoramosDC** [comment]
Hi, trevorwang,

I found this library: https://github.com/journeyapps/zxing-android-embedded,
and it works very well in LG K10.

Maybe you update you Dart Lib, the problem will be solved.

I hope for the best

See ya

**Comment by trevorwang** [comment]
@rodrigoramosDC  Thanks in advance. Will update that library later.

**Comment by trevorwang** [comment]
@rodrigoramosDC I have upgrade that lib to 3.6.0. You can have a try on this lib@0.3.9
